describe('details page', () => {
  it('creates map with markers using lat long columns', () => {
    cy.visit('http://localhost:3000/datensaetze/25')
    cy.contains('Polizeidienststellen')
    cy.contains('Karte erstellen').click()
    cy.contains('Wähle dazu die Spalten aus, die ')
    cy.contains('Breitengrad').find('select').select('latitude')
    cy.contains('Längengrad').find('select').select('longitude')
    cy.contains('Karte erstellen').click()
    cy.get('.leaflet-marker-icon')
    cy.contains('Wähle dazu die Spalten aus, die ').should('not.exist')
  })
})

describe('details page', () => {
  it('creates map with markers using adress columns', () => {
    cy.visit('http://localhost:3000/datensaetze/25')
    cy.contains('Polizeidienststellen')
    cy.contains('Karte erstellen').click()
    cy.contains('die ein Teil der Adresse beinhalten:')
      .next()
      .contains('city')
      .click({ force: true })
    cy.contains('die ein Teil der Adresse beinhalten:')
      .next()
      .contains('zipcode')
      .click({ force: true })
    cy.contains('die ein Teil der Adresse beinhalten:')
      .next()
      .contains('street')
      .click({ force: true })
    cy.contains('die ein Teil der Adresse beinhalten:')
      .next()
      .contains('houseNumber')
      .click({ force: true })
    cy.contains('die ein Teil der Adresse beinhalten:')
      .parent()
      .contains('Karte erstellen')
      .click({ force: true })
    cy.get('.leaflet-marker-icon')
    cy.contains('Wähle dazu die Spalten aus, die ').should('not.exist')
  })
})
