describe('details page', () => {
  it('creates map with markers using lat long columns where correct naming is allready present', () => {
    cy.visit('http://localhost:3000/')
    cy.get('input').type('polizei')
    cy.contains('Polizeidienststellen').click({ force: true })
    cy.contains('Karte erstellen').click()
    cy.contains('Wähle dazu die Spalten aus, die ')
    cy.contains('Breitengrad').find('select').select('latitude')
    cy.contains('Längengrad').find('select').select('longitude')
    cy.contains('Karte erstellen').click()
    cy.get('.leaflet-marker-icon')
    cy.contains('Wähle dazu die Spalten aus, die ').should('not.exist')
  })

  it('creates map with markers using lat long columns where correct naming is not present', () => {
    cy.visit('http://localhost:3000/')
    cy.get('input').type('Pegel Stammdaten')
    cy.contains('Pegel Stammdaten').click({ force: true })
    cy.contains('Karte erstellen').click({ force: true })
    cy.contains('Wähle dazu die Spalten aus, die ')
    cy.contains('Breitengrad')
      .find('select')
      .select('geogrBreite', { force: true })
    cy.contains('Längengrad')
      .find('select')
      .select('geogrLaenge', { force: true })
    cy.contains('Karte erstellen').click({ force: true })
    cy.get('.leaflet-marker-icon')
    cy.contains('Wähle dazu die Spalten aus, die ').should('not.exist')
  })

  it('creates map with markers using adress columns', () => {
    cy.visit(
      'http://localhost:3000/datensaetze/5cac7e8ad6821af36c27077674c9fe4d'
    )
    cy.contains('Karte erstellen').click()
    cy.contains('die ein Teil der Adresse beinhalten:')
      .next()
      .contains('LAGE')
      .click({ force: true })
    cy.contains('die ein Teil der Adresse beinhalten:')
      .next()
      .contains('ORT')
      .click({ force: true })
    cy.contains('die ein Teil der Adresse beinhalten:')
      .parent()
      .contains('Karte erstellen')
      .click({ force: true })
    cy.wait(10000)
    cy.get('.leaflet-marker-icon')
    cy.contains('Wähle dazu die Spalten aus, die ').should('not.exist')
  })

  it('shows error message when choosing the wrong coordinate columns', () => {
    cy.visit('http://localhost:3000/')
    cy.get('input').type('polizei')
    cy.contains('Polizeidienststellen').click({ force: true })
    cy.contains('Karte erstellen').click()
    cy.contains('Wähle dazu die Spalten aus, die ')
    cy.contains('Breitengrad').find('select').select('id')
    cy.contains('Längengrad').find('select').select('id')
    cy.contains('Karte erstellen').click()
    cy.contains('Es werden keine Daten auf der Karte angezeigt.')
  })
})
